config/routes.rb
Rails.application.routes.draw do
  root "welcome#about"

  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get 'users/:id', to: "users#show", as: "profile"

  # Skills
  post '/skill/sit', to: "messages#sit"
  post '/skill/shuffle', to: "messages#shuffle"
  post '/skill/use', to: "messages#skill"
  post '/game/start_end', to: "messages#start_end"

  resources :chatrooms, param: :slug
  resources :messages
  resources :users

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :slugify

  attr_accessor :cure_rules, :poison_rule, :guard_rule, :thief_rule, :seer, :witch, :hunter, :defender, :elder, :thief, :villager, :werewolf, :whitewolf

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all

    # delete chatroom name room
    # chatrooma = Chatroom.find_by(slug: "new")
    # unless chatrooma.nil?
    #   chatrooma.destroy
    # end
  end

  def new
    if !request.referrer.nil? && request.referrer.split("/").last == "chatrooms"
      flash[:notice] = nil
    end
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def create
    # logger.info("=============== In create ====================")
    # logger.info("#{params.as_json}")
    begin
      message_content = build_first_message(params[:chatroom])
      # logger.info("#{message_content}")
      if chatroom_params['topic'].strip == "new"
        raise ChatroomsHelper::ChatroomCreateError.new("new不是一个合法的名字 GG")
      end
      @chatroom = Chatroom.new(chatroom_params)
      if @chatroom.save
        user = User.find_by(:id => 1)
        message = Message.new(:chatroom_id => @chatroom.id, :user => user, :content => message_content)
        if message.save
          respond_to do |format|
            format.html { redirect_to @chatroom }
            format.js
          end
        else
          raise ChatroomsHelper::ChatroomCreateError.new("创建房间失败 GG")
        end
      else
        raise ChatroomsHelper::ChatroomCreateError.new("房名空或已存在 GG")
      end
    rescue ChatroomsHelper::ChatroomCreateError => error
      respond_to do |format|
        flash[:notice] = {ERROR: ["#{error.message}"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'}
      end
    end
  end

  def update
    chatroom = Chatroom.find_by(slug: params[:slug])
    chatroom.update(chatroom_params)
    redirect_to chatroom
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @chatroom_message = @chatroom.messages
    @display_message = [@chatroom.messages.order('created_at').last]
    @current_user = current_user
    @message = Message.new

    begin
      @hash = JSON.parse(@display_message.last.content)
      @seats = build_seats_array(@hash['seats'], @hash['room_size'].to_i)
    rescue JSON::ParserError
      @hash = {}
      @seats = []
    end
  end

  def destroy
    # logger.info("=============== In destroy ====================")
    # logger.info("#{params.as_json}")
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @chatroom.destroy

    redirect_to chatrooms_path
  end

  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end

    def build_seats_array(hash, room_size)
      array = Array.new
      (1..room_size).each do |i|
        seat = Seat.new
        seat.number = i
        seat.user = hash[i.to_s]['user']
        seat.role = hash[i.to_s]['role']
        seat.status = hash[i.to_s]['status']
        array.push(seat)
      end
      array
    end

    def build_first_message(params)
      seer = params[:seer].to_i
      witch = params[:witch].to_i
      hunter = params[:hunter].to_i
      defender = params[:defender].to_i
      thief = params[:thief].to_i
      elder = params[:elder].to_i
      villager = params[:villager].to_i
      whitewolf = params[:whitewolf].to_i
      werewolf = params[:werewolf].to_i

      room_size = seer + witch + hunter + defender + thief + elder + villager + whitewolf + werewolf

      if room_size <= 0
        raise ChatroomsHelper::ChatroomCreateError.new("至少要有一个角色")
      end
      if thief >= 1
        room_size -= 2
      end

      roles = Array.new
      if seer >= 1
        roles.push(SEER)
      end

      if witch >= 1
        roles.push(WITCH)
      end

      if hunter >= 1
        roles.push(HUNTER)
      end

      if defender >= 1
        roles.push(DEFENDER)
      end

      if thief >= 1
        roles.push(THIEF)
      end

      if elder >= 1
        roles.push(ELDER)
      end

      if whitewolf >= 1
        roles.push(WHITEWOLF)
      end

      (1..villager).each do |i|
        roles.push(WHITEWOLF)
      end

      (1..werewolf).each do |i|
        roles.push(WEREWOLF)
      end

      string = "{\"cure_rules\":\"#{params[:cure_rules]}\", \"poison_rule\":\"#{params[:poison_rule]}\", \"guard_rule\":\"#{params[:guard_rule]}\", \"thief_rule\":\"#{params[:thief_rule]}\", \"room_size\":\"#{room_size}\", "
      string = string + " \"seats\":{ "
      (1..room_size).each do |i|
        string = string + "\"#{i}\":{\"user\":\"EMPTY_SEAT_USER\", \"role\":\"EMPTY_ROLE\", \"status\":\"NORMAL\"},"
      end
      string = string[0..-2] #remove last ,
      string = string + "}, \"roles\":{"

      roles.each_with_index { |item, index|
        string = string + " \"#{index}\": \"#{item}\","
      }
      string = string[0..-2] #remove last ,
      string = string + "}, \"started\": \"false\", \"master_user\": \"EMPTY_SEAT_USER\", \"turn\": \"EMPTY_ROLE\"}"
      string
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
    class ChatroomCreateError < StandardError; end
end

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">topic:</span>
      <%= f.text_field :topic, class: "form-control"%>
    </div>
    <br>
      <ul class="list-group">
        <li class="list-group-item">
          <div class="form-check form-check-inline">
            <label class="form-check-label name-label">
              第一夜自救 <%= f.radio_button :cure_rules, "FirstNightSave", checked: true %>
            </label>

            <label class="form-check-label name-label">
              不可自救 <%= f.radio_button :cure_rules, "CannotSaveSelf" %>
            </label>

            <label class="form-check-label">
              可以自救 <%= f.radio_button :cure_rules, "CanSaveSelf" %>
            </label>
          </div>
        </li>
        <li class="list-group-item">
          <div class="form-check form-check-inline">
            <label class="form-check-label name-label">
              不可和解药同夜使用 <%= f.radio_button :poison_rule, "CannotUseCurePoisonSameNight", checked: true %>
            </label>

            <label class="form-check-label">
              可以和解药同夜使用 <%= f.radio_button :poison_rule, "CanUseCurePoisonSameNight" %>
            </label>
          </div>
        </li>
        <li class="list-group-item">
          <div class="form-check form-check-inline">
              <label class="form-check-label name-label">
                同守同救算死亡 <%= f.radio_button :guard_rule, "GuardAndCuredIsDead", checked: true %>
              </label>

              <label class="form-check-label">
                同守同救算存活 <%= f.radio_button :guard_rule, "GuardAndCuredIsAlive" %>
              </label>
          </div>
        </li>
        <li class="list-group-item">
          <div class="form-check form-check-inline">
            <label class="form-check-label name-label">
              有狼必须选狼 <%= f.radio_button :thief_rule, "MustPickWerewolf", checked: true %>
            </label>

            <label class="form-check-label">
               随意挑选 <%= f.radio_button :thief_rule, "AllPick" %>
             </label>
          </div>
        </li>
        <li class="list-group-item">
          <div class="form-check form-check-inline">
            <label class="form-check-label name-label">
              预言家 <%= f.check_box :seer %>
            </label>
            <label class="form-check-label name-label">
              女巫 <%= f.check_box :witch %>
            </label>
            <label class="form-check-label name-label">
              猎人 <%= f.check_box :hunter %>
            </label>
            <label class="form-check-label name-label">
              守卫 <%= f.check_box :defender %>
            </label>
            <label class="form-check-label name-label">
              长老 <%= f.check_box :elder %>
            </label>
            <label class="form-check-label name-label">
              盗贼 <%= f.check_box :thief %>
            </label>
            <label class="form-check-label">
              村民 <%= f.select :villager, (0..8) %>
            </label>
          </div>
        </li>
        <li class="list-group-item">
          <div class="form-check form-check-inline">
            <label class="form-check-label name-label">
              白狼王 <%= f.check_box :whitewolf %>
            </label>
            <label class="form-check-label">
              狼人 <%= f.select :werewolf, (0..8) %>
            </label>
          </div>
        </li>
      </ul>
    <%= f.submit '创建房间', class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/chatroom_error.js.erb
$("input#chatroom_topic").val("");
$("#chatroom-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/chatrooms/create.js.erb
$("input#chatroom_topic").val(" ")
$("#chatroom-errors").html(" ")
$("#chatroom-index").append('<li><%= link_to @chatroom.topic, chatroom_path(@chatroom) %></li>')

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>所有房间</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
    <ul id="chatroom-index"> 
      <% if @chatrooms.any? %>
        <%= render @chatrooms%>
      <%else %>
    </ul>
    <p>还没有房间!</p>
  <% end %>
  <div id="chatroom-errors">  
  </div>
  <h2>创建房间</h2>
  <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
</div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">

  <h1>Create a Chatroom on a programming topic</h1>
    <div class="well">
      <div class="chatroom-form">
        <%= form_for @chatroom do |f| %>
          <div class="input-group">
            <span class="input-group-addon">topic:</span>
            <%= f.text_field :topic, class: "form-control"%>
          </div>
          <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
        <% end %>
      </div>
    </div>

    <%= render partial: 'layouts/flash_errors'%>
</div>

app/views/chatrooms/show.html.erb
<% @debugMode = false %>
<% @editMessage = false %>
<% @gameStarted = (@hash['started'] == 'true') %>
<div class="data-div" type=hidden>
  <%= render partial: 'messages/message_data', locals: {current_message: @display_message, this_user: @current_user}%>
</div>

<div id="game-error">
</div>


<div class="row col-md-8 col-md-offset-2">
  <div id="topic-panel">
    <h1><%= @chatroom.topic %></h1><h5>  <%= link_to '删除房间', chatroom_path(@chatroom), method: :delete, data: { confirm: '确定删除房间?' }%></h5>
    <h5 id="topic-panel-current-turn-h"><%=@hash['turn_display']%></h5>
  </div>

  <% shrink = @gameStarted ? 'shrink' : '' %>
  <div id="seats-panel" class="container-fluild <%=shrink%>">
    <%= render partial: 'seats/seat', collection: @seats%>
  </div>

  <br/>

  <div id="identity-panel">
  </div>
  <div id="skill-panel">
    <%= render partial: 'messages/skill', locals: {message: @display_message.last, user: @current_user, chatroom: @chatroom} %>
  </div>

  <div id="lasnightinfo-panel">
    <% if @gameStarted %>
      <% if @hash.include? 'last_night_info_display'%>
        <%=@hash['last_night_info_display']%>
      <% else %>
        无昨夜信息
      <% end %>
    <% else %>
    昨夜信息: 游戏尚未开始
    <% end %>
  </div>

  <div class="panel panel-default" id="info-panel">
    <% if @chatroom_message.any? %>
      <div class="panel-body" id="messages">
        <%= render partial: 'messages/message', collection: @chatroom_message%>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>

  <% if @editMessage %>
    <div>
      <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
    </div>
    <div>
      <%= render partial: 'messages/edit_message_form', locals: {message: @display_message, chatroom: @chatroom}%>
    </div>
  <% end %>

<footer>
    <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container row col-md-8 col-md-offset-2 ">
          <div class="center">
            <div class="action-button-div">
              <button type="button" id="useskill" class="btn btn-primary" onclick="useskill()">使用技能</button>
            </div>

            <div class="action-button-div">
              <button type="button" id="identity" class="btn btn-primary" onclick="identity()">身份配置</button>
            </div>

            <div class="action-button-div">
              <button type="button" id="lastnightinfo" class="btn btn-warning" onclick="lastnightinfo()">昨夜信息</button>
            </div>

            <div class="action-button-div">
              <%= render partial: 'messages/start_end_game', locals: {message: @display_message.last, user: @current_user, chatroom: @chatroom} %>
            </div>

            <div class="action-button-div" id="shuffle-btn-div">
              <%= render partial: 'messages/shuffle' %>
            </div>
          </div>
        </div>
    </div>
</footer>

</div>